Vagrant.configure("2") do |config|
  config.vm.define "vm1" do |vm|
    vm.vm.box = "jaca1805/debian12"
    vm.vm.network "private_network", type: "static", ip: "192.168.33.44"
    vm.vm.synced_folder "", "/home/vagrant/config"
  end
end
