# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "ansible" do |ansible|
    ansible.vm.box = "jaca1805/debian12"
    ansible.vm.network "private_network", type: "static", ip: "192.168.33.5"

    ansible.vm.synced_folder "C:/Travail/config", "/home/vagrant/config"

    ansible.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    ansible.vm.provision "shell", path: "ansible.sh"
  end
end